### PR TITLE
ISSUE-13 Responsive design

### PR DESCRIPTION
**Pull request by GustavoMantuan**
#13

### CODE REVIEW

**Comment by TheWillG** [comment]
@GustavoMantuan this looks really good, thank you I will review this today.

**Comment by TheWillG** [comment]
@GustavoMantuan please fast forward with master branch and resolve conflicts

**Comment by GustavoMantuan** [comment]
@TheWillG Hey, code updated!

**Comment by TheWillG** [comment]
Looks great, thanks for the contribution @GustavoMantuan

**Pull request merged**
