### PR TITLE
Sorting items by date (Newest to Oldest)

### LINKED ISSUE #24: Sort table items based on date
- [ ] When rendering the projects table, sort the projects with the newest projects at the top.

### PR DESCRIPTION
**Pull request by keeganthomp**
closes #24

### CODE REVIEW

**Comment by keeganthomp** [comment]
Ah fudge...yep. Sorry about that. I’ll fix this weekend. Any preference on how I handle this?

**Comment by TheWillG** [comment]
@keeganthomp just setting it to the existing `projects` state variable should be fine. Thanks

**Comment by TheWillG** [comment]
Also are you sure you are actually sorting so that the newest project is at the top of the list? I'm demoing the app with this code and the newest project is on bottom.

**Comment by keeganthomp** [comment]
Yep. Might need to be reversed depending on how you want it sorted. Currently, it is sorting oldest to newest. To reverse, just need to switch the ‘a’ and ‘b’ in the return. 

Do you want it newest to oldest or oldest to newest?

**Comment by TheWillG** [comment]
Newest to oldest

**Comment by keeganthomp** [comment]
@TheWillG Check out latest update. Let me know if still not what you wanted

**Pull request merged**
