### PR TITLE
made clickable chips and sort accordingly

### LINKED ISSUE #35: Sort when Tech chip clicked
- [ ] Make Tech chips on table clickable

- [ ] When clicking Tech chip, highlight this clicked chip and add the chip under the "Search" bar to show that this chip is being added to the search.

- [ ] Sort using the chip value on top of the existing search bar

- [ ] Also, pick your favorite open source project and add it to the app!!

Use clean code and best practices.

### PR DESCRIPTION
**Pull request by thakursaurabh1998**
fixes #35 @TheWillG

### CODE REVIEW

**Comment by thakursaurabh1998** [comment]
@TheWillG any changes required?

**Comment by TheWillG** [comment]
Will review these PRS today, thanks

**Comment by TheWillG** [comment]
@thakursaurabh1998 PR #36 and PR #37 both solve this in different ways, but PR #36 is closer to what I was looking for UI/UX only because I wanted the chips to show on top of the table instead of adding to the search filter.

**Comment by thakursaurabh1998** [comment]
But the searching part doesn't seem to be idle  I can add that chip. @TheWillG

**Comment by TheWillG** [comment]
@thakursaurabh1998 Yes, your PR works exactly as I wanted, but we need the chips to appear on top of the table instead of adding text to the search bar.

**Comment by TheWillG** [comment]
@thakursaurabh1998 Also, we need to allow the user to select more than 1 chip. Right now, only 1 chip is allowed to be clicked.

**Comment by thakursaurabh1998** [comment]
@TheWillG  Ok upto you 👍

**Pull request closed without merging**
