### PR TITLE
#28: Added CSS design to Home and Project page!

### PR DESCRIPTION
**Pull request by Vishal1541**

### CODE REVIEW

**Comment by TheWillG** [comment]
Will review today thanks

**Comment by TheWillG** [comment]
The NEW icon looks like it is inconsistent. Can you fix it so it looks the same on every row?

**Comment by Vishal1541** [comment]
@TheWillG  #28: Fixed the NEW Icon - Home page 
css2

**Comment by TheWillG** [comment]
I like it but can we go back to the yellow icons for now?

**Comment by Vishal1541** [comment]
@TheWillG  #28: Fix- yellow color NEW Icon 
css3

**Pull request merged**
