### PR TITLE
Issue#28: Redesigned project page

### PR DESCRIPTION
**Pull request by mahamshahid18**
#28 Added a new design for the project page

Hey @TheWillG you can take a look at this design as well, in case you like it. I know you closed the issue but I was already working on it so I thought I should complete it :)

image

### CODE REVIEW

**Comment by TheWillG** [comment]
Oh nice

**Comment by TheWillG** [comment]
So I was in the process of moving all the CSS from the.css files into the React components in the form of a Javascript styles object. I want to maintain one pattern for styles instead of having two different ones. 

Can you convert your CSS from the .css file into Javascript?

**Comment by TheWillG** [comment]
If that is too much trouble I will take it like this and do it myself later. I like your design and want to go with it

**Comment by mahamshahid18** [comment]
Thanks. Glad you like it :)

I'm not sure how that works exactly since I'm not very proficient with JSX just yet (still learning). Do you mean inline styles? Like in this file: https://github.com/TheWillG/CodeRally/blob/master/src/components/Project/Project.js

**Comment by TheWillG** [comment]
Yup inline styles

**Comment by mahamshahid18** [comment]
@TheWillG I've moved the css styles into the React component. Feel free to take a look and merge it in if you're happy with it :)

**Comment by mahamshahid18** [comment]
Might I also suggest an improvement. The way I have designed the page, the `chip elements` in the project card would look better if the tech stack is not a string, instead it's an array of items. This way, a chip can be generated for each element (each item in the tech stack). I think that will look better instead of one comma separated string. Same thing for the resources needed.

Thought I should share the idea :)

**Comment by TheWillG** [comment]
Yes I have been thinking about doing the same thing with the chips for the input form exactly how you have said. It would require accepting techs in the input form and saving the techs as an array so then on the project page we can easily show the array of chips. 

Great suggestion. I will create an issue for it now. Would you be interested in working on it?

**Comment by mahamshahid18** [comment]
Perfect. Please mention me once you create the issue for this

**Pull request merged**
